export const SEND_APPLICATION_REQUEST = 'SEND_APPLICATION_REQUEST';
export const SEND_APPLICATION_SUCCESS = 'SEND_APPLICATION_SUCCESS';
export const SEND_APPLICATION_FAILURE = 'SEND_APPLICATION_FAILURE';
export const SEND_APPLICATION_LOADING_INDICATOR = 'SEND_APPLICATION_LOADING_INDICATOR';
